export const FETCH_TODOS_1 = "FETCH_TODOS_1";
export const FETCH_TODOS_1_SUCCESS = "FETCH_TODOS_1_SUCCESS";
export const FETCH_TODOS_1_FAILED = "FETCH_TODOS_1_FAILED";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const CHANGE_TASK_TITLE = "CHANGE_TASK_TITLE";
